apiVersion: apps/v1
kind: Deployment

metadata:
  name: wil-playground
  namespace: dev

spec:
  replicas: 1
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app: wil-playground

  template:
    metadata:
      labels:
        app: wil-playground

    spec:
      containers:
        - name: wil-playground
          image: wil42/playground:v1

          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service

metadata:
  name: wil-playground-service
  namespace: dev

spec:
  selector:
    app: wil-playground

  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---
# Ingress: Expose the App from the exterior of the CLUSTER
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: wil-ingress             # Ingress name (used for network rule)
  namespace: dev                # Target ArgoCD namespace

spec:
  rules:
    - host: wil.local          # Must set up /etc/hosts pointing to the IP of the CLUSTER. Used for Host header.

      http:
        paths:
          - path: /            # ... Starting with
            pathType: Prefix   # Every incoming HTTP requests ...

            backend:
              service:                        # Service used within wil.local.http requests
                name: wil-playground-service  # Target service as backend

                port:
                  number: 8888                # Exposed port for incoming requests

